name: PyTEI
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - numpy=1.23.5
  - pandas=1.5.3
  - pytorch
  - scikit-learn=1.2.2
  - pip:
      - timm==0.6.12
      - torchfm==0.7.0